# Generated by Django 3.1.3 on 2020-11-17 23:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miercoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sabado'), ('7', 'Domingo')], max_length=1)),
                ('apertura', models.TimeField()),
                ('cierre', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='PuntoDeRetiro',
            fields=[
                ('nodo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sucursal_crud_api.nodo')),
                ('capacidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            bases=('sucursal_crud_api.nodo',),
        ),
        migrations.AddField(
            model_name='nodo',
            name='ubicacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sucursal_crud_api.ubicacion', verbose_name='Ubicacion'),
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('nodo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sucursal_crud_api.nodo')),
                ('direccion', models.CharField(max_length=100)),
                ('disponibilidad', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='sucursal_crud_api.horario', verbose_name='Horario')),
            ],
            bases=('sucursal_crud_api.nodo',),
        ),
    ]
