# Generated by Django 3.1.3 on 2020-11-15 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (7, 'Domingo')], max_length=1)),
                ('apertura', models.TimeField()),
                ('cierre', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('ubicacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sucursal_crud_api.ubicacion', verbose_name='relacion_ubicacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PuntoDeRetiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('ubicacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sucursal_crud_api.ubicacion', verbose_name='relacion_ubicacion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
