# Generated by Django 3.1.3 on 2020-11-15 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal_crud_api', '0002_sucursal_disponibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='disponibilidad',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='sucursal_crud_api.horario', verbose_name='r_horario'),
        ),
    ]
